### ISSUE TITLE
Todo v0.0.3

### ISSUE THREAD

**Issue by pierreguillot** [Musicoll/Kiwi#22]
- [ ] Add jObject method : getTextToDisplay()
- [ ] See if we can declare the objects model and objects engine another way 
- [ ] Add model namespace to Atom
- [ ] Sortir les TypedObjects et les mettre dans un module ("Module Name"/Model et "Module Name"/Engine) -> Repenser pour la v0.0.3
- [ ] Gestion des erreurs
- [ ] Check nested class model::Patcher, model::Patcher::User, model::Patcher::View
- [x] Encodage dans la box (déclenche jassert en mode debug)
- [ ] Corde invisible quand objet lointain
